// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravellerFeedBackAPI.Models;

#nullable disable

namespace TravellerFeedBackAPI.Migrations
{
    [DbContext(typeof(FeedBackContext))]
    [Migration("20230805175723_Feedbackae")]
    partial class Feedbackae
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TravellerFeedBackAPI.Models.UserFeedBack", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<double?>("Ratings")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int>("TravellerId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.ToTable("UserFeedBacks");
                });
#pragma warning restore 612, 618
        }
    }
}
